- name: Create Folder - {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.29.153:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: create pipeline job
  ansible.builtin.include_tasks: pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"
