- name: config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job-{{item.name}}].xml

- name: Create job - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job-{{item.name}}].xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.29.153:8080
    user: admin
    password: "{{jenkins_password}}"


#- name: create config
#  ansible.builtin.template:
#    src: s-job.xml
#    dest: /tmp/s-job.xml
#
#- name: Create a jenkins job using basic authentication
#  community.general.jenkins_job:
#    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
#    name: "{{item.dir}}/{{item.name}} "
#    url: http://172.31.9.180:8080
#    user: admin
#    password: "{{jenkins_Password}}"